services:
  - type: web
    name: quadball-game
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python -m uvicorn main:app --host 0.0.0.0 --port $PORT
    routes:
      - path: /
        matchType: prefix
    staticPublishPath: ./static
